version: 2

sphinx:
  builder: dirhtml
  configuration: docs/conf.py
  fail_on_warning: true

build:
  os: ubuntu-22.04
  tools:
    python: 3.11

python:
  install:
  - method: pip
    path: .
  - requirements: docs/requirements.txt
  system_packages: false
