# .readthedocs.yml
version: 2

# Build configuration
sphinx:
  configuration: docs/conf.py  # 如果你的配置文件是 docs/conf.py
python:
  version: 3.10  # 如果你使用的是 Python 3.8，修改为适合的版本
  install:
    - requirements: docs/requirements.txt  # 如果需要安装依赖
    - method: pip
