"""Reviewed legacy error templates; translate whole messages before formatting.

Card operations carry their own templates. These entries also cover legacy
callers which flatten exceptions to strings. Keep placeholders as opaque data.
"""

RUNTIME_ERROR_TEMPLATES = (
    ('CardOperationError', 'At least one dopant ratio must be positive.'),
    ('CardOperationError', 'At least one replacement probability must be positive.'),
    ('CardOperationError', 'BainPath ca_range values must be positive.'),
    ('CardOperationError', 'BainPath coordinate_mode must be relative_ca or axis_scale.'),
    ('CardOperationError', 'BainPath requires a nonsingular 3x3 cell.'),
    ('CardOperationError', 'BainPath volume_scale_range values must be positive.'),
    ('CardOperationError', 'CellScaling: engine_type must be 0 (Sobol) or 1 (Uniform).'),
    ('CardOperationError', 'CellScaling: max_scaling must be finite and non-negative.'),
    ('CardOperationError', 'CellStrain requires a nonsingular 3x3 cell.'),
    ('CardOperationError', 'Composition Gradient axis must be one of a, b, or c.'),
    ('CardOperationError', 'Composition Gradient requires a non-singular 3D cell to use lattice directions a, b, or c.'),
    ('CardOperationError', 'Composition Gradient requires valid start and end compositions.'),
    ('CardOperationError', 'Composition Gradient target mode must be all or listed.'),
    ('CardOperationError', 'Composition Space Sampling budget allocation must be Equal+Reflow, Capacity-weighted, or Equal (legacy).'),
    ('CardOperationError', 'Composition Space Sampling method must be Grid or Sobol.'),
    ('CardOperationError', 'Composition Space Sampling seed must be non-negative.'),
    ('CardOperationError', 'Correlated Random Spin requires vector magnetic moments or liftable scalar magmoms.'),
    ('CardOperationError', 'Correlated Random Spin: cone_angle must be within [0, 180] degrees.'),
    ('CardOperationError', 'Correlated Random Spin: correlation_length must be positive.'),
    ('CardOperationError', 'Correlated Random Spin: magnitude_source must be Existing initial magmoms or Map/default magnitude.'),
    ('CardOperationError', 'Correlated Random Spin: max_atoms_for_full must be >= 1.'),
    ('CardOperationError', 'Correlated Random Spin: samples must be >= 1.'),
    ('CardOperationError', 'Correlated Random Spin: seed must be >= 0.'),
    ('CardOperationError', "Correlated Random Spin: unsupported correlation_kernel '{value}'."),
    ('CardOperationError', "Correlated Random Spin: unsupported mode '{value0}'."),
    ('CardOperationError', "Dopant ratio_type must be 'atom' or 'mass'."),
    ('CardOperationError', 'Dopant ratios must be finite and non-negative.'),
    ('CardOperationError', 'FPS Filter: backend must be auto, cpu, or cuda.'),
    ('CardOperationError', 'FPS Filter: {name} must be >= {minimum}.'),
    ('CardOperationError', 'FPS Filter: {name} must be a finite number.'),
    ('CardOperationError', 'FPS Filter: {name} must be an integer.'),
    ('CardOperationError', 'Finite-Cell Alloy Occupancy: arrangements_per_composition must be >= 1.'),
    ('CardOperationError', "Finite-Cell Alloy Occupancy: atoms.arrays['sublattice'] must be one label per atom."),
    ('CardOperationError', 'Finite-Cell Alloy Occupancy: count bounds for {label}.{element} must be integers.'),
    ('CardOperationError', 'Finite-Cell Alloy Occupancy: elements for {label} must be a list or string.'),
    ('CardOperationError', 'Finite-Cell Alloy Occupancy: fixed composition for {label} is invalid.'),
    ('CardOperationError', 'Finite-Cell Alloy Occupancy: fixed fractions for {label} must sum to 1.'),
    ('CardOperationError', 'Finite-Cell Alloy Occupancy: invalid range for {label}.{element}.'),
    ('CardOperationError', 'Finite-Cell Alloy Occupancy: invalid site_rules JSON: {reason}.'),
    ('CardOperationError', 'Finite-Cell Alloy Occupancy: max_outputs must be >= 1.'),
    ('CardOperationError', 'Finite-Cell Alloy Occupancy: rule for {label} must be an object.'),
    ('CardOperationError', 'Finite-Cell Alloy Occupancy: seed must be >= 0 when use_seed is enabled.'),
    ('CardOperationError', 'Finite-Cell Alloy Occupancy: site_rules must be a non-empty JSON object.'),
    ('CardOperationError', 'Finite-Cell Alloy Occupancy: sublattice labels must be non-empty.'),
    ('CardOperationError', 'Finite-Cell Alloy Occupancy: unsupported mode {mode} for {label}; use fixed_fraction, fraction_range, or count_range.'),
    ('CardOperationError', 'Finite-Cell Alloy Occupancy: {field_name} for {label} must be an object.'),
    ('CardOperationError', 'Finite-Cell Alloy Occupancy: {field_name} keys for {label} must exactly match its allowed elements.'),
    ('CardOperationError', 'Geometry Filter: {name} must be a finite non-negative number.'),
    ('CardOperationError', 'InsertDefect: could not place atom {value0} of {count} for output {value2} after {max_attempts} attempts ({mode_name}); reduce the minimum distance or insertion count.'),
    ('CardOperationError', 'InsertDefect: invalid weight for element {value0}.'),
    ('CardOperationError', 'InsertDefect: weight for {symbol} must be finite and positive.'),
    ('CardOperationError', 'InsertDefect: {label} must be >= 1.'),
    ('CardOperationError', 'InsertDefect: {label} must be an integer.'),
    ('CardOperationError', 'Integer scan range must contain exactly three values: start, stop, step.'),
    ('CardOperationError', 'Integer scan range step must be positive.'),
    ('CardOperationError', 'Invalid replacement JSON: {reason}'),
    ('CardOperationError', 'LayerCopy: dz expression is empty.'),
    ('CardOperationError', 'MagneticOrder: AFM group labels must be non-empty.'),
    ('CardOperationError', "MagneticOrder: AFM group mode requires atoms.arrays['group']; add Layer Groups upstream or choose k-vector mode."),
    ('CardOperationError', 'MagneticOrder: PM cone angle must be between 0 and 180 degrees.'),
    ('CardOperationError', 'MagneticOrder: reference axis must be a finite nonzero 3-vector.'),
    ('CardOperationError', 'MagneticOrder: seed must be nonnegative.'),
    ('CardOperationError', 'MagneticOrder: unsupported PM direction {value0}.'),
    ('CardOperationError', 'MagneticOrder: unsupported {label} {text}.'),
    ('CardOperationError', 'Manual atom pair canting requires the same number of left and right indices.'),
    ('CardOperationError', 'Minimum element fraction must be between 0 and 1.'),
    ('CardOperationError', 'Ordered Alloy Prototype: a_range values must be finite and positive.'),
    ('CardOperationError', 'Ordered Alloy Prototype: c/a must be finite and positive.'),
    ('CardOperationError', 'Ordered Alloy Prototype: invalid sublattice_elements JSON: {reason}.'),
    ('CardOperationError', 'Ordered Alloy Prototype: max_outputs must be >= 1.'),
    ('CardOperationError', 'Ordered Alloy Prototype: sublattice_elements JSON must be an object.'),
    ('CardOperationError', 'Ordered Alloy Prototype: unsupported prototype {text}; choose one of {supported}.'),
    ('CardOperationError', 'Perturb: engine_type must be 0 (Sobol) or 1 (Uniform).'),
    ('CardOperationError', 'Perturb: max_distance values must be finite and non-negative.'),
    ('CardOperationError', 'RandomDoping rule use must be atomic_percent, mass_percent, or count.'),
    ('CardOperationError', 'Range must contain exactly three values: start, stop, step.'),
    ('CardOperationError', 'Range step must be positive.'),
    ('CardOperationError', 'Range values must be finite.'),
    ('CardOperationError', 'Replacement JSON must be an object.'),
    ('CardOperationError', 'Replacement probabilities must be finite and non-negative.'),
    ('CardOperationError', 'Replacement ratios must be finite and non-negative.'),
    ('CardOperationError', 'Scan range must contain exactly three values: start, stop, step.'),
    ('CardOperationError', 'Scan range step must be positive.'),
    ('CardOperationError', 'Scan range values must be finite.'),
    ('CardOperationError', 'ShearAngle requires a finite, right-handed 3x3 cell.'),
    ('CardOperationError', 'ShearMatrix requires a finite, right-handed 3x3 cell.'),
    ('CardOperationError', "SmallAngleSpinTilt group-pair mode requires atoms.arrays['group']."),
    ('CardOperationError', "SmallAngleSpinTilt group-pair mode requires nonzero magnetic atoms in both groups '{group_a}' and '{group_b}'."),
    ('CardOperationError', "SmallAngleSpinTilt pair_group_filter requires atoms.arrays['group']."),
    ('CardOperationError', 'SmallAngleSpinTilt requires usable initial magnetic moments; provide initial_magmoms or select Map/default magnitude.'),
    ('CardOperationError', 'SmallAngleSpinTilt: canting_mode must be Global tilt, Single-spin tilt, Atom pair canting, or Group pair canting.'),
    ('CardOperationError', 'SmallAngleSpinTilt: max_outputs must be >= 1.'),
    ('CardOperationError', 'SmallAngleSpinTilt: max_outputs must be >= 2 when include_reference is enabled.'),
    ('CardOperationError', 'Solvation: cannot parse solvent_xyz: {reason}'),
    ('CardOperationError', 'Solvation: flex_pool must be >= 1.'),
    ('CardOperationError', 'Solvation: solvent_count must be >= 1.'),
    ('CardOperationError', 'Solvation: solvent_xyz is empty.'),
    ('CardOperationError', "Solvent Box Fill: count_mode must be 'fixed' or 'density'."),
    ('CardOperationError', 'Solvent Box Fill: density must be positive.'),
    ('CardOperationError', 'Solvent Box Fill: fill_packing must be greater than 0 and at most 1.'),
    ('CardOperationError', 'Solvent Box Fill: sampling_mode must be one of auto, general, water, loose, dense.'),
    ('CardOperationError', 'Solvent Box Fill: solvent mass must be positive.'),
    ('CardOperationError', 'Spin Disorder cone_angle must be within [0, 180] degrees.'),
    ('CardOperationError', 'Spin Disorder fractions must be finite values within (0, 1].'),
    ('CardOperationError', 'Spin Disorder magnitude_source must be Existing initial magmoms or Map/default magnitude.'),
    ('CardOperationError', 'Spin Disorder max_outputs must be >= 1.'),
    ('CardOperationError', 'Spin Disorder mode must be Flip fraction, Cone disorder, or Randomize fraction.'),
    ('CardOperationError', 'Spin Disorder samples_per_fraction must be >= 1.'),
    ('CardOperationError', 'Spin Disorder seed must be >= 0.'),
    ('CardOperationError', 'StackingFault layers must be >= 1.'),
    ('CardOperationError', 'StackingFault requires at least one atom.'),
    ('CardOperationError', 'StackingFault step must contain exactly three values: start, stop, step.'),
    ('CardOperationError', 'SuperCell: fixed_axis_scale values must be positive integers.'),
    ('CardOperationError', 'SuperCell: mode must be scale, cell, or max_atoms.'),
    ('CardOperationError', 'SuperCell: output_mode must be single or enumerate.'),
    ('CardOperationError', 'SuperCell: super_scale values must be positive integers.'),
    ('CardOperationError', 'SuperCell: target_cell values must be positive.'),
    ('CardOperationError', 'SuperCell: target_policy must be at_least or at_most.'),
    ('CardOperationError', 'SuperCell: {name} must contain three finite values.'),
    ('CardOperationError', "Unsupported FPS strategy '{value0}'. Expected one of {value1}."),
    ('CardOperationError', 'Unsupported bond_filter_mode: {value0}'),
    ('CardOperationError', 'Unsupported boolean operator: {value0}'),
    ('CardOperationError', 'Unsupported operator: {value0}'),
    ('CardOperationError', 'Unsupported syntax: {value0}'),
    ('CardOperationError', 'Unsupported unary operator: {value0}'),
    ('CardOperationError', 'count values must be >= 0.'),
    ('CardOperationError', 'count values must be integers.'),
    ('CardOperationError', 'count_mode must be fixed or random.'),
    ('CardOperationError', 'dz expression is empty'),
    ('CardOperationError', 'dz expression returned shape {value0}, expected {value1}'),
    ('CardOperationError', 'percent must be within [0, 100].'),
    ('CardOperationError', '{label} minimum must be <= maximum.'),
    ('CardOperationError', '{label} must contain exactly three values: start, stop, step.'),
    ('CardOperationError', '{label} must contain one or two values.'),
    ('CardOperationError', '{label} must not be empty.'),
    ('CardOperationError', '{label} step must be positive.'),
    ('CardOperationError', '{label} values must be finite.'),
    ('CardOperationError', '{prefix}: {key} must be >= {minimum}.'),
    ('CardOperationError', '{prefix}: {key} must be a finite number.'),
    ('CardOperationError', '{prefix}: {key} must be an integer.'),
    ('RuntimeMessage', "'all' cannot be combined with explicit sublattice labels."),
    ('RuntimeMessage', "'species' not found in atomic_properties and no usable 'species_id'/'type_map'"),
    ('RuntimeMessage', 'A NEP angular cutoff cannot exceed its radial cutoff.'),
    ('RuntimeMessage', 'A structure has invalid PBC metadata.'),
    ('RuntimeMessage', 'A structure has invalid positions or cell data.'),
    ('RuntimeMessage', 'ASE trajectory PBC must contain exactly three logical values.'),
    ('RuntimeMessage', 'ASE trajectory cell must be a finite 3 x 3 matrix.'),
    ('RuntimeMessage', 'ASE trajectory per-atom array {name} has unsupported dtype {value1}.'),
    ('RuntimeMessage', 'ASE trajectory per-atom array {name} is empty.'),
    ('RuntimeMessage', 'ASE trajectory per-atom array {name} must have shape N or N x M.'),
    ('RuntimeMessage', 'ASE trajectory positions must be finite N x 3 values.'),
    ('RuntimeMessage', 'ASE trajectory {tensor_name} must contain nine finite tensor values.'),
    ('RuntimeMessage', "Atomic expression fields must use 'atomic.<name>'."),
    ('RuntimeMessage', "Atomic field 'atomic.{alias}' does not support value views."),
    ('RuntimeMessage', 'Built-in workflow templates cannot be deleted.'),
    ('RuntimeMessage', 'Built-in workflow templates cannot be modified.'),
    ('RuntimeMessage', 'Built-in workflow templates cannot be renamed.'),
    ('RuntimeMessage', "Builtin field '{base}' does not support attribute '{value1}'."),
    ('RuntimeMessage', 'CP2K force count does not match the imported coordinate count.'),
    ('RuntimeMessage', 'CP2K output contains an invalid or singular cell.'),
    ('RuntimeMessage', 'CP2K output is missing complete CELL vectors; NepTrainKit will not invent a unit cell.'),
    ('RuntimeMessage', 'Cannot export an empty DeepMD dataset.'),
    ('RuntimeMessage', 'Cannot validate {value0}: {reason}. Move the manifest aside to treat the .out files as external results.'),
    ('RuntimeMessage', 'Composition JSON must be an object mapping element->fraction.'),
    ('RuntimeMessage', 'Composition ratio for {symbol} must be finite.'),
    ('RuntimeMessage', 'Composition ratio for {symbol} must be non-negative.'),
    ('RuntimeMessage', 'DeepMD Config_type {config_key} has an invalid cell.'),
    ('RuntimeMessage', 'DeepMD Config_type {config_key} has an invalid virial.'),
    ('RuntimeMessage', 'DeepMD Config_type {config_key} has invalid positions.'),
    ('RuntimeMessage', 'DeepMD NPY (Mixed) structures in the same padded atom-count group must share PBC mode, per-atom fields, and label coverage.'),
    ('RuntimeMessage', 'DeepMD dataset {folder_path} is missing type_map.raw; chemical species cannot be reconstructed safely.'),
    ('RuntimeMessage', 'DeepMD dataset {folder_path}, frame {index} has an invalid box.'),
    ('RuntimeMessage', 'DeepMD dataset {folder_path}, frame {index} has invalid coordinates.'),
    ('RuntimeMessage', 'DeepMD export cannot represent partial PBC for Config_type {config_key}.'),
    ('RuntimeMessage', 'DeepMD export cannot represent partial PBC.'),
    ('RuntimeMessage', 'DeepMD export failed and the previous dataset could not be restored automatically. The previous dataset is retained at: {retained}'),
    ('RuntimeMessage', 'DeepMD export requires explicit PBC metadata for Config_type {config_key}.'),
    ('RuntimeMessage', 'DeepMD export requires explicit PBC metadata.'),
    ('RuntimeMessage', 'DeepMD mixed atom_numb_pad must be positive or None.'),
    ('RuntimeMessage', 'DeepMD mixed export cannot contain empty structures.'),
    ('RuntimeMessage', 'DeepMD per-atom field {key} has unsupported dtype {value1}.'),
    ('RuntimeMessage', 'DeepMD per-atom field {name} has shape {value1}, expected {expected_shape}.'),
    ('RuntimeMessage', 'DeepMD per-atom field {source_name} has shape {value1}, expected {expected_shape}.'),
    ('RuntimeMessage', 'DeepMD periodic Config_type {config_key} requires a nonsingular cell.'),
    ('RuntimeMessage', 'DeepMD periodic structures require a nonsingular cell.'),
    ('RuntimeMessage', 'DeepMD set_size must be positive.'),
    ('RuntimeMessage', 'DeepMD structure has an invalid cell.'),
    ('RuntimeMessage', 'DeepMD structure has an invalid virial.'),
    ('RuntimeMessage', 'DeepMD structure has invalid positions.'),
    ('RuntimeMessage', 'DeepMD type_map must contain unique element symbols.'),
    ('RuntimeMessage', 'Direction vector must be nonzero.'),
    ('RuntimeMessage', 'EXTXYZ Lattice must contain exactly nine finite values.'),
    ('RuntimeMessage', 'EXTXYZ Properties is required.'),
    ('RuntimeMessage', 'EXTXYZ Properties must include species and pos.'),
    ('RuntimeMessage', 'EXTXYZ atom count must be non-negative.'),
    ('RuntimeMessage', 'EXTXYZ pbc must contain exactly three logical values.'),
    ('RuntimeMessage', 'EXTXYZ pos must be a finite N x 3 array.'),
    ('RuntimeMessage', 'EXTXYZ pos must use pos:R:3.'),
    ('RuntimeMessage', 'EXTXYZ property names must be non-empty and unique.'),
    ('RuntimeMessage', 'EXTXYZ property {name} has shape {value1}, expected {expected_shape}.'),
    ('RuntimeMessage', 'EXTXYZ property {name} is missing from atom rows.'),
    ('RuntimeMessage', 'EXTXYZ property {name} must have a positive column count.'),
    ('RuntimeMessage', 'EXTXYZ species data is missing.'),
    ('RuntimeMessage', 'EXTXYZ species must use species:S:1.'),
    ('RuntimeMessage', 'EXTXYZ {key} must be a finite scalar.'),
    ('RuntimeMessage', 'EXTXYZ {key} must contain six or nine finite values.'),
    ('RuntimeMessage', 'Existing training dataset does not exist: {existing_path}'),
    ('RuntimeMessage', 'Expression contains unsupported syntax.'),
    ('RuntimeMessage', 'Expression must be a condition. Add a comparison, for example: natoms > 100.'),
    ('RuntimeMessage', 'Expression must reference at least one structure field.'),
    ('RuntimeMessage', 'Expression result shape does not match active structures.'),
    ('RuntimeMessage', 'Failed to import structures from {candidate}: {value1}'),
    ('RuntimeMessage', 'Failed to read ASE trajectory {candidate}: {reason}'),
    ('RuntimeMessage', "Failed to read dataset '{value0}'."),
    ('RuntimeMessage', 'Failed to resolve LAMMPS atom types {missing}: {reason}'),
    ('RuntimeMessage', "Field '{base}' does not support value views."),
    ('RuntimeMessage', "Field '{label}' requires an explicit component or '.norm'."),
    ('RuntimeMessage', "Field '{value0}' does not support '.{view}'."),
    ('RuntimeMessage', 'Grid simplex points for order>=4 require step ~= 1/n.'),
    ('RuntimeMessage', 'Incomplete EXTXYZ frame: atom count and header are required.'),
    ('RuntimeMessage', 'Invalid EXTXYZ atom count.'),
    ('RuntimeMessage', 'Invalid EXTXYZ column count for property {name}.'),
    ('RuntimeMessage', 'Invalid EXTXYZ logical value: {value}'),
    ('RuntimeMessage', 'Invalid LAMMPS atom count in frame {timestep}: {value1}'),
    ('RuntimeMessage', 'Invalid LAMMPS timestep value: {value0}'),
    ('RuntimeMessage', 'Invalid element symbol: {text}'),
    ('RuntimeMessage', 'Invalid expression syntax.'),
    ('RuntimeMessage', 'Invalid magmom vector for {symbol}: {val}'),
    ('RuntimeMessage', 'Invalid workflow identifier.'),
    ('RuntimeMessage', 'Invalid workflow kind.'),
    ('RuntimeMessage', 'LAMMPS frame {timestep} contains invalid element symbols: {invalid_species}'),
    ('RuntimeMessage', 'LAMMPS frame {timestep} does not declare three BOX BOUNDS boundary flags'),
    ('RuntimeMessage', 'LAMMPS frame {timestep} has invalid BOX BOUNDS'),
    ('RuntimeMessage', 'LAMMPS frame {timestep} has invalid atom count {n_atoms}'),
    ('RuntimeMessage', "LAMMPS frame {timestep} is missing 'ITEM: ATOMS'"),
    ('RuntimeMessage', "LAMMPS frame {timestep} is missing 'ITEM: BOX BOUNDS'"),
    ('RuntimeMessage', "LAMMPS frame {timestep} is missing 'ITEM: NUMBER OF ATOMS'"),
    ('RuntimeMessage', 'LAMMPS frame {timestep} is missing the atom count'),
    ('RuntimeMessage', 'LAMMPS frame {timestep} is truncated: expected {n_atoms} atom rows, found {i}'),
    ('RuntimeMessage', 'LAMMPS frame {timestep} must contain an element or type column'),
    ('RuntimeMessage', 'LAMMPS frame {timestep} must contain one complete coordinate triplet: xs/ys/zs, x/y/z, or xu/yu/zu'),
    ('RuntimeMessage', 'LAMMPS frame {timestep}, atom row {value1} has invalid atom type {tnum}'),
    ('RuntimeMessage', 'LAMMPS frame {timestep}, atom row {value1} has invalid integer type {val}'),
    ('RuntimeMessage', 'LAMMPS frame {timestep}, atom row {value1} has {value2} columns; expected {value3}'),
    ('RuntimeMessage', 'LAMMPS numeric atom types require an explicit element mapping; unresolved types: {unresolved}'),
    ('RuntimeMessage', 'Local Chemistry requires finite positions and a nonsingular periodic cell.'),
    ('RuntimeMessage', 'Magmom JSON must be an object mapping element->moment.'),
    ('RuntimeMessage', 'Malformed EXTXYZ atom row {row_index}: expected {expected_columns} columns, found {value2}.'),
    ('RuntimeMessage', 'Missing DFT {quantity}; using NEP {quantity2} instead.'),
    ('RuntimeMessage', 'ModelVersion {model_id} not found'),
    ('RuntimeMessage', 'NEP cutoff line does not match the declared element count.'),
    ('RuntimeMessage', 'NEP cutoffs must be finite and positive.'),
    ('RuntimeMessage', 'NEP file does not exist: {model_path}'),
    ('RuntimeMessage', 'NEP model does not contain a cutoff line.'),
    ('RuntimeMessage', 'NEP model file is empty.'),
    ('RuntimeMessage', 'NEP model header does not match the declared element count.'),
    ('RuntimeMessage', 'NEP model header has an invalid element count.'),
    ('RuntimeMessage', 'Non-physical structure scanning requires the native audit extension.'),
    ('RuntimeMessage', 'Project {project} not found'),
    ('RuntimeMessage', 'Provided species length does not match counts in XDATCAR'),
    ('RuntimeMessage', 'Raw structure descriptors are required for physics-aware recommendations.'),
    ('RuntimeMessage', 'Raw structure descriptors do not align with the active dataset.'),
    ('RuntimeMessage', 'Requires a finite cell and at least one periodic axis. Keeps the host and fills the whole cell.'),
    ('RuntimeMessage', 'Rule for {label} contains unsupported fields: {value1}.'),
    ('RuntimeMessage', 'Rule for {label} must be an object.'),
    ('RuntimeMessage', 'Site-set labels must be non-empty.'),
    ('RuntimeMessage', 'Structured balanced FPS requires a positive sample limit.'),
    ('RuntimeMessage', 'Structures in DeepMD Config_type {config_key} must share atom types, PBC mode, per-atom fields, and label coverage.'),
    ('RuntimeMessage', 'The largest structure has {largest_structure} atoms, above the CUDA workspace estimate of {recommended}. Use CPU for this dataset; a single structure cannot be split safely.'),
    ('RuntimeMessage', 'TorsionGuard: pbc=yes requires a finite, nonsingular 3x3 cell.'),
    ('RuntimeMessage', 'TorsionGuard: pbc_mode must be auto, yes, or no.'),
    ('RuntimeMessage', 'Truncated LAMMPS dump: missing timestep value'),
    ('RuntimeMessage', 'Unsupported DeepMD NPY format: {format}'),
    ('RuntimeMessage', 'Unsupported EXTXYZ property type {dtype}.'),
    ('RuntimeMessage', 'Unsupported expression syntax.'),
    ('RuntimeMessage', 'Unsupported k-vector {value}; use 100, 010, 001, 110, or 111.'),
    ('RuntimeMessage', "Unsupported suffix for atomic field 'atomic.{alias}'."),
    ('RuntimeMessage', "Unsupported suffix for field '{base}'."),
    ('RuntimeMessage', 'Unsupported {value0} schema. Move the manifest aside to treat the .out files as external results.'),
    ('RuntimeMessage', 'Update check failed with HTTP {value0}{detail}'),
    ('RuntimeMessage', 'Workflow configuration must be a JSON object.'),
    ('RuntimeMessage', 'Workflow configuration must contain a card list.'),
    ('RuntimeMessage', 'atomic descriptors must align with structure atom counts'),
    ('RuntimeMessage', 'atomic descriptors must be finite'),
    ('RuntimeMessage', 'atomic descriptors must match the model descriptor dimension'),
    ('RuntimeMessage', 'chunk_max_atoms must be positive'),
    ('RuntimeMessage', 'cone_component must be in [-1, 1]'),
    ('RuntimeMessage', 'descriptors must be a finite two-dimensional array'),
    ('RuntimeMessage', 'existing descriptors must be finite and match the candidate feature dimension'),
    ('RuntimeMessage', 'geometry contains an unsupported atomic number'),
    ('RuntimeMessage', 'global anisotropy scan must include a zero-coordinate reference'),
    ('RuntimeMessage', 'initial_magmoms must be a finite numeric N or N x 3 array'),
    ('RuntimeMessage', 'input_type must be int or float'),
    ('RuntimeMessage', 'invalid response coordinate {token}'),
    ('RuntimeMessage', 'magmoms must be a finite numeric N or N x 3 array'),
    ('RuntimeMessage', 'magnetoelastic structural and spin scans must include zero'),
    ('RuntimeMessage', 'min_distance must be non-negative'),
    ('RuntimeMessage', 'min_fraction must be finite and non-negative.'),
    ('RuntimeMessage', 'min_fraction must be in [0, 1].'),
    ('RuntimeMessage', 'moment magnitude response must include scale factor 1.0'),
    ('RuntimeMessage', 'moment scale factors must be non-negative'),
    ('RuntimeMessage', "n2p2 block {block_idx} is missing its closing 'end'."),
    ('RuntimeMessage', 'n2p2 block {block_idx} must contain zero or three lattice rows.'),
    ('RuntimeMessage', 'n2p2 line {line_number} has unsupported element {elem}.'),
    ('RuntimeMessage', 'n2p2 line {line_number} has {value1} atom columns; expected 10.'),
    ('RuntimeMessage', 'n_samples must be positive'),
    ('RuntimeMessage', 'order must be >= 2'),
    ('RuntimeMessage', 'period must be positive'),
    ('RuntimeMessage', 'q response scan must include q=0'),
    ('RuntimeMessage', 'reference_structures is required for REF_GROUP_ALIGNMENT'),
    ('RuntimeMessage', 'response scan coordinates must be finite'),
    ('RuntimeMessage', 'response scan coordinates must be unique'),
    ('RuntimeMessage', 'response scan requires at least {minimum_points} distinct coordinates'),
    ('RuntimeMessage', 'rotation response scan must include a zero-coordinate reference'),
    ('RuntimeMessage', 'sample_cap_per_stratum must be positive'),
    ('RuntimeMessage', 'scalar magmoms require a finite nonzero axis for spin:R:3'),
    ('RuntimeMessage', 'scale_factor must be >= 1'),
    ('RuntimeMessage', 'site_rules must be a non-empty JSON object.'),
    ('RuntimeMessage', 'spin must be a finite numeric N x 3 array'),
    ('RuntimeMessage', 'step must be in (0, 1].'),
    ('RuntimeMessage', 'structure descriptors must align with structures'),
    ('RuntimeMessage', 'structure descriptors must be finite'),
    ('RuntimeMessage', 'surface normal must not be parallel to q for a cycloidal spiral'),
    ('RuntimeMessage', 'the detected spin model requires canonical spin:R:3 in every candidate; first missing structure: {first}'),
    ('RuntimeMessage', 'the detected spin model requires canonical spin:R:3 in the existing training set; first missing structure: {first}'),
    ('RuntimeMessage', 'unsupported local response kind: {value0}'),
    ('RuntimeMessage', 'unsupported structural response mode: {value0}'),
    ('RuntimeMessage', 'unsupported texture response kind: {value0}'),
    ('RuntimeMessage', '{key} must contain start, stop, and step'),
    ('RuntimeMessage', '{tag} already exists, please delete it first'),
    ('RuntimeMessage', 'MagneticOrder: no nonzero magnetic moments; set an element moment or a nonzero unlisted-element moment.'),
    ('RuntimeMessage', 'MagneticOrder: the selected k-vector produces only one AFM sign on magnetic atoms; expand the cell or choose another vector.'),
    ('RuntimeMessage', 'LayerCopy: unsupported apply_mode {mode}.'),
    ('RuntimeMessage', 'Failed to load dataset: {reason}. If official NEP .out files already exist, keep a complete set of energy, force, virial, and stress or mforce outputs in the dataset directory.'),
    ('RuntimeMessage', 'Loading existing official NEP .out files without opening the model. descriptor.out is missing, so descriptor plots and FPS are unavailable. Install a nep-adapters version that supports this model to generate descriptors.'),
    ('RuntimeMessage', 'NEP Auto selected CPU because CUDA is unavailable ({reason}). The calculation will continue on CPU. To enable CUDA, install a Linux CPU+CUDA nep-adapters wheel with a compatible NVIDIA driver.'),
    ('RuntimeMessage', 'Spin Disorder requires vector magnetic moments or liftable scalar magmoms.'),
)

DIAGNOSTIC_TEMPLATES = (
    'Cartesian position filter returned an invalid shape.',
    'Contact summary shape {value0} does not match {expected_shape}.',
    'Direction vector is zero, cannot normalize.',
    'Dopant item count must be non-negative.',
    'Expected {expected_version}, loaded {value1}.',
    'Failed to allocate exact counts.',
    'FastScatterVisual pos must have shape (N, 2) or (N, 3)',
    'Finite-cell composition unranking failed.',
    'GeometryFilter mass_density requires positive volume.',
    'Histogram bins and structure indices must have matching sizes.',
    'Histogram bins must be non-negative.',
    'Internal unlike-species matching failed.',
    "Invalid indexing mode. Accepts: None, 'faces'",
    "NEP cutoff scope must be 'radial' or 'angular'.",
    'Previous runtime-package directory is missing: {target}',
    'Project already exists or could not be created: {value0}',
    'ResultData must be moved from its current owner thread',
    'Seed package directory does not exist: {target}',
    'The cached physical partitions do not cover source structure {value0}.',
    'Unsupported comparison operator.',
    'Unsupported coordinate shape: {value0}',
    'Unsupported params type: {value0}',
    'Unsupported selection mode: {mode}',
    'candidate sampling feature blocks must not be empty',
    'catalog root must be a JSON object',
    'cells and pbc must contain the same number of structures',
    'cutoff must be finite and non-negative',
    'cutoff must be finite and positive',
    'each cell and pbc value must have shape (3, 3) and (3,)',
    'each cell must have shape (3, 3)',
    'each pbc value must have shape (3,)',
    'each positions array must have shape (N, 3)',
    'existing feature blocks and existing plan must be supplied together',
    'existing_descriptors and existing_plan must be supplied together',
    'generated invalid magnetic response groups: {reasons}',
    'group_list must be one dimensional',
    'input_type must be str or list',
    'invalid catalog JSON: {reason}',
    'manifest task_id values must be unique',
    'model {value0} cannot be its own parent',
    'model {value0} references missing parent {value1}',
    'models must be a JSON array',
    'native cell scanner returned an invalid result shape',
    'native collision scanner returned an invalid result shape',
    'native short-distance scanner returned an invalid result shape',
    'nep_energy_array is required for DFT_TO_NEP_ALIGNMENT',
    'parent must be TreeItem or int',
    'path is required when structures are not provided',
    'physics plan groups must cover each descriptor row exactly once',
    'points and selected_data must have the same feature dimension',
    'points must be two dimensional',
    'positions must have shape (n, 3)',
    'positions, cells, and pbc must contain the same number of structures',
    'prediction parts must not be empty',
    'project must be a JSON object',
    'radius coefficient must be finite and non-negative',
    'scale_factor must be an array-like of length 3',
    'selected_data must contain at least one row',
    'source must be a JSON object',
    'source_indices must align with the structure sequence.',
    'target_coverage must be in (0, 1]',
    'unit_str must be str or list',
    'unsupported catalog schema_version={schema_version}; expected {CATALOG_SCHEMA_VERSION}',
    'unsupported magnetic response params: {value0}',
    'unsupported sampling coverage policy: {coverage_policy}',
    'unsupported sampling recommendation policy: {policy}',
    'value and base cannot both be None',
    '{label} replacement count must be >= 0.',
    '{location} must be a JSON object',
    '{location}.id must be a unique non-negative integer',
    '{location}.tags must be a JSON array',
    '{location}.{key} must be a non-empty string',
    'signs shape mismatch',
)
