name: Build with Nuitka and Upload to Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Existing Tag (e.g., v1.0)'
        required: true

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install imageio
          mkdir -p  ${{ github.workspace }}/src/build/main.dist/

#      - name: Build with Nuitka
#        uses: Nuitka/Nuitka-Action@main
#        with:
#          nuitka-version: main
#          script-name: NepTrainKit/main.py
#          include-package: NepTrainKit
#          output-file: NepTrainKit.exe
#          mode: standalone
#          windows-console-mode: disable
#          include-qt-plugins: sqldrivers
#          include-package-data: vispy
#          upx-binary: ${{ github.workspace }}/src/NepTrainKit/upx${{ runner.os == 'Windows' && '.exe' || '' }}
#          enable-plugins: pyside6,upx
#          windows-icon-from-ico: NepTrainKit/src/images/logo.png
#          working-directory: ${{ github.workspace }}/src/

      - name: Copy additional files
        shell: pwsh
        run: |
          cp -r ${{ github.workspace }}/src/NepTrainKit/Config ${{ github.workspace }}/src/build/main.dist/
          cp -r ${{ github.workspace }}/src/NepTrainKit/update.exe ${{ github.workspace }}/src/build/main.dist/update.exe
          mkdir -p ${{ github.workspace }}/src/build/main.dist/Log

      - name: Package artifacts (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Set-Location ${{ github.workspace }}/src/build/main.dist/
          $compress = @{
            Path = "*"
            CompressionLevel = "Fastest"
            DestinationPath = "${{ github.workspace }}/NepTrainKit-${{ inputs.tag_name }}-windows.zip"
          }
          Compress-Archive @compress
          Write-Host "Package created at ${{ github.workspace }}/NepTrainKit-${{ inputs.tag_name }}-windows.zip"

      # 新增：重命名文件
      - name: Rename Release Asset
        shell: pwsh
        run: |
          $originalFile = "${{ github.workspace }}/NepTrainKit-${{ inputs.tag_name }}-windows.zip"
          $newFile = "${{ github.workspace }}/NepTrainKit.win32.zip"  # 修改为你想要的名称
          Move-Item -Path $originalFile -Destination $newFile -Force
          Write-Host "Renamed file to $newFile"

      - name: Verify File Exists
        shell: pwsh
        run: |
          $filePath = "${{ github.workspace }}/NepTrainKit.win32.zip"
          if (-not (Test-Path -Path $filePath)) {
            Write-Error "File not found: $filePath"
            exit 1
          }
          Write-Host "File exists: $filePath"

      - name: Create and Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag_name }}
          name: Release ${{ inputs.tag_name }}
          body: |
            Release for NepTrainKit ${{ inputs.tag_name }} (Windows)
            - Built with Nuitka
            - Includes latest updates
          files: ${{ github.workspace }}/NepTrainKit.win32.zip  # 使用重命名后的文件
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact (backup)
        uses: actions/upload-artifact@v4
        with:
          name: NepTrainKit-${{ matrix.os }}-${{ inputs.tag_name }}
          path: ${{ github.workspace }}/NepTrainKit.win32.zip