# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Install OpenMP (macOS only)
      if:  matrix.os == 'macos-latest'
      run: |
          brew install libomp
          echo "OMP_INCLUDE_PATH=$(brew --prefix libomp)/include" >> $GITHUB_ENV
          echo "OMP_LIB_PATH=$(brew --prefix libomp)/lib" >> $GITHUB_ENV
    - name: Install dependencies
      shell: bash -l {0}  # 确保使用 bash shell
      run: |
        python -m pip install --upgrade pip
        pip install build   pybind11 setuptools setuptools-scm -U
          if [[ matrix.os == 'ubuntu-latest' ]]; then pip install auditwheel; fi
          if [[ matrix.os == 'windows-latest' ]]; then pip install delvewheel; fi
          if [[ matrix.os == 'macos-latest' ]]; then pip install delocate; fi
#
#    - name: clear
#      run: |
#        rm -rf build/ dist/ *.egg-info
#

    - name: Build package
      shell: bash -l {0}  # 确保使用 bash shell
      env:
        # 仅在 macOS 上传递 OpenMP 参数
          CFLAGS: ${{ matrix.os == 'macos-latest' && '-Xpreprocessor -fopenmp -I$OMP_INCLUDE_PATH' || '' }}
          LDFLAGS: ${{ matrix.os == 'macos-latest' && '-L$OMP_LIB_PATH -lomp' || '' }}
      run: |
        python setup.py bdist_wheel
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then auditwheel repair dist/*.whl -w dist/; fi
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then delvewheel repair dist/*.whl -w dist/; fi
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then delocate-wheel dist/*.whl -w dist/; fi
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        path: dist/*.whl
        name: wheels-${{ matrix.os }}-py${{ matrix.python-version }}
#    - name: Publish package
#      uses: pypa/gh-action-pypi-publish@release/v1
#      with:
#        user: __token__
#        password: ${{ secrets.PYPI_API_TOKEN }}
#        packages_dir: dist
#        skip_existing: false
    - name: Publish to PyPI
      run: |
        pip install twine
        twine upload --username __token__ --password ${{ secrets.PYPI_API_TOKEN }} dist/*
      shell: bash